### ISSUE TITLE
Windows build

### ISSUE THREAD

**Issue by isuruf** [conda-forge/mpfr-feedstock#2]
See https://github.com/BrianGladman/mpfr

Is it possible add two sources in meta.yaml? One for unix and one for windows?

**Comment by pelson** [comment]
> Is it possible add two sources in meta.yaml? One for unix and one for windows?

It is, thanks to selectors:

```
package:
  name: foo

source:
  url: http://usual_source  # [not win]
  url: http://windows_source  # [win]
```
